os: linux
dist: bionic
language: java

install:
  # install without any testing to get dependencies in place
  - mvn install -Dmaven.test.skip=true -B -V -fae

script:
  # execute unit and integration tests
  - mvn -e -fae -B -Dfailsafe.useFile=false clean test verify
  # check javadoc for lint
  - if [ "$TRAVIS_JDK_VERSION" == openjdk8 ]; then
         mvn javadoc:javadoc;
         mvn javadoc:test-javadoc;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
      - graphviz

jdk:
  - openjdk8
  - openjdk11

jobs:
  fast_finish: true

cache:
  directories:
  - $HOME/.m2
