init:
  - git config --global core.autocrlf true
  - git config --global core.safecrlf true

clone_folder: C:\projects\openls-databinding

# can't use shallow clone because we need to convert line endings in test expectations
shallow_clone: false

version: "{build}-{branch}"

skip_tags: true

install:
  - mvn install -Dmaven.test.skip=true -B -V -fae

build: off

test_script:
  - cd C:\projects\openls-databinding
  - mvn -e -fae -B -Dfailsafe.useFile=false clean test verify

environment:

  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

cache:
  - C:\Users\appveyor\.m2\repository -> pom.xml
