init:
  - git config --global core.autocrlf true
  - git config --global core.safecrlf true

clone_folder: C:\projects\openls-databinding

# can't use shallow clone because we need to convert line endings in test expectations
shallow_clone: false

version: "{build}-{branch}"

skip_tags: true

install:
  - ps: >-
      Add-Type -AssemblyName System.IO.Compression.FileSystem
          if (!(Test-Path -Path "C:\maven" )) {
            (new-object System.Net.WebClient).DownloadFile(
              'http://www.us.apache.org/dist/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.zip',
              'C:\maven-bin.zip'
            )
            [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
          }
  - cmd: SET PATH=C:\maven\apache-maven-3.3.3\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: echo %PATH%
  - cmd: java -version
  - cd C:\projects\openls-databinding
  - mvn install -U -Dmaven.test.skip=true -B -V -fae -e -T2.2C

build: off

test_script:
  - cd C:\projects\openls-databinding
  - mvn -e -fae -B -Dfailsafe.useFile=false -T2 clean test

environment:

  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

#matrix:
#  fast_finish: true
#  allow_failures:
#    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0

cache:
  - C:\maven\apache-maven-3.3.3 -> appveyor.yml
  - C:\Users\appveyor\.m2\repository -> pom.xml
